<a href="https://colab.research.google.com/github/parth22X/AIML_Lab_22csu336/blob/main/Exp2_22csu336.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [3]:
import numpy as np
array1 = np.array([1, 22, 4, 5])
array2 = np.array([7, 11, 3, 8])
array3 = np.array([2, 13, 6, 9])

# Adding the three arrays
added_array = array1 + array2 + array3

# Sorting the added array
sorted_added_array = np.sort(added_array)

# Displaying the results
print("Added Array:", added_array)
print("Sorted Added Array:", sorted_added_array)


Added Array: [10 46 13 22]
Sorted Added Array: [10 13 22 46]


In [4]:
d=np.array([(1,2,3),(4,5,6)])
e=np.array([(7,3,1),(14,15,36)])
print(d+e)
print(e)

[[ 8  5  4]
 [18 20 42]]
[[ 7  3  1]
 [14 15 36]]


In [5]:
g=np.zeros((3,3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
i=np.arange(10,25,5)
i

array([10, 15, 20])

In [7]:
k=np.full((2,2),7)
k

array([[7, 7],
       [7, 7]])

In [8]:
l=np.eye(2)
l

array([[1., 0.],
       [0., 1.]])

In [9]:
n=np.random.random((2,2))
n

array([[0.59787899, 0.89450437],
       [0.18615631, 0.75239068]])

In [10]:
ones_array = np.ones((3, 4))
print("Ones Array:\n", ones_array)

Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
empty_array = np.empty((2, 3))
print("Empty Array:\n", empty_array)

Empty Array:
 [[3.95e-323 2.47e-323 1.98e-323]
 [8.89e-323 9.88e-323 2.08e-322]]


In [12]:
np.info(np.ones)

 ones(shape, dtype=None, order='C', *, like=None)

Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and order.

See Also
--------
o

In [13]:
array_to_save = np.array([1, 2, 3, 4, 5])
np.save('saved_array.npy', array_to_save)

In [14]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Saving the arrays to a file
np.savez('saved_arrays.npz', array1=array1, array2=array2)

In [15]:
loaded_array = np.load('saved_array.npy')
print("Loaded Array:", loaded_array)

# Loading multiple arrays from a .npz file
loaded_arrays = np.load('saved_arrays.npz')
print("Loaded Array 1:", loaded_arrays['array1'])
print("Loaded Array 2:", loaded_arrays['array2'])

Loaded Array: [1 2 3 4 5]
Loaded Array 1: [1 2 3]
Loaded Array 2: [4 5 6]


In [16]:
np.savetxt('data.txt', np.array([[1.5, 2.5], [3.5, 4.5]]), delimiter=',')

# Loading the data from the text file
loaded_txt_array = np.loadtxt('data.txt', delimiter=',')
print("Loaded Text Array:\n", loaded_txt_array)

Loaded Text Array:
 [[1.5 2.5]
 [3.5 4.5]]


In [17]:
with open('data_with_missing.txt', 'w') as f:
    f.write('1.0, 2.0, 3.0\n')
    f.write('4.0, , 6.0\n')
    f.write('7.0, 8.0, 9.0\n')

# Loading the data from the text file, treating missing values as NaN
loaded_genfromtxt_array = np.genfromtxt('data_with_missing.txt', delimiter=',')
print("Loaded Genfromtxt Array:\n", loaded_genfromtxt_array)

Loaded Genfromtxt Array:
 [[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]]
