<a href="https://colab.research.google.com/github/parth22X/AIML_Lab_22csu336/blob/main/Copy_of_Python_Codes_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:

a = np.array([1, 2, 3, 4])



In [ ]:
b = np.array([5, 6, 7, 8])

In [ ]:
c = np.array([9, 10, 11, 12])

In [ ]:
d = a+b+c

In [ ]:
print(d)

[15 18 21 24]


In [ ]:
d.sort()

In [ ]:
d


array([15, 18, 21, 24])

In [ ]:

e = np.array([(1, 2, 3), (4, 5, 6)], dtype=float)
print(e)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:

e = np.array([(1, 2, 3), (4, 5, 6)], dtype=float)
print(e)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
g = np.zeros((3,3))

In [ ]:
g


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:

e = np.array([(1, 2, 3), (4, 5, 6)], dtype=float)
print(e)

g = np.zeros((2, 3))  # Adjusted shape to match 'e'
s = e * g
print(s)


[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
h = np.ones((2,4))
h

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
i = np.arange(10,25,5)
i

array([10, 15, 20])

In [ ]:
i

array([10, 15, 20])

In [ ]:
j = np.linspace(0,2,9)

In [ ]:
j

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
k  = np.full((2,2),7)
k

array([[7, 7],
       [7, 7]])

In [ ]:
l = np.eye(2)
l

array([[1., 0.],
       [0., 1.]])

In [ ]:
n = np.random.random((2,2))
n

array([[0.71152908, 0.74754439],
       [0.22784596, 0.82481526]])

In [ ]:
import pandas as pd
import numpy as np

# Creating a Pandas DataFrame from a dictionary
data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'Salary': [50000, 60000, 70000, 80000, 90000]
}

df = pd.DataFrame(data_dict)
print("DataFrame created from a dictionary:")
print(df)

# Basic statistics
print("\nBasic statistics:")
print(df.describe())

# Adding a new column
df['Bonus'] = df['Salary'] * 0.10
print("\nDataFrame after adding a 'Bonus' column:")
print(df)

# Filtering data
high_salary_df = df[df['Salary'] > 60000]
print("\nFiltered DataFrame where 'Salary' > 60000:")
print(high_salary_df)

# Grouping data
grouped_df = df.groupby('Age').sum()
print("\nGrouped DataFrame by 'Age':")
print(grouped_df)

# Handling missing data
df_with_nan = df.copy()
df_with_nan.loc[2, 'Salary'] = np.nan
print("\nDataFrame with NaN value:")
print(df_with_nan)

# Filling missing data
df_filled = df_with_nan.fillna(df_with_nan['Salary'].mean())
print("\nDataFrame after filling NaN values with the mean salary:")
print(df_filled)

# Dropping missing data
df_dropped = df_with_nan.dropna()
print("\nDataFrame after dropping rows with NaN values:")
print(df_dropped)

# Merging DataFrames
additional_data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Department': ['HR', 'Engineering', 'Finance', 'Marketing', 'Sales']
}
df_additional = pd.DataFrame(additional_data)

merged_df = pd.merge(df, df_additional, on='Name')
print("\nMerged DataFrame:")
print(merged_df)

# Pivot table
pivot_df = merged_df.pivot_table(values='Salary', index='Department', columns='Age', aggfunc=np.mean)
print("\nPivot Table:")
print(pivot_df)

# Sorting DataFrame by multiple columns
sorted_df = df.sort_values(by=['Age', 'Salary'], ascending=[True, False])
print("\nDataFrame sorted by 'Age' (ascending) and 'Salary' (descending):")
print(sorted_df)

# Applying functions to DataFrame columns
import pandas as pd

# Example DataFrame creation (replace this with your actual DataFrame)
data = {
    "Salary": [50000, 60000, 70000, 80000]
}
df = pd.DataFrame(data)

# Apply a 5% increase to 'Salary' using vectorized operations
df['Adjusted Salary'] = df['Salary'] * 1.05

# Display the DataFrame after applying the increase
print("\nDataFrame after applying a 5% increase to 'Salary':")
print(df)



DataFrame created from a dictionary:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    David   40   80000
4      Eva   45   90000

Basic statistics:
             Age        Salary
count   5.000000      5.000000
mean   35.000000  70000.000000
std     7.905694  15811.388301
min    25.000000  50000.000000
25%    30.000000  60000.000000
50%    35.000000  70000.000000
75%    40.000000  80000.000000
max    45.000000  90000.000000

DataFrame after adding a 'Bonus' column:
      Name  Age  Salary   Bonus
0    Alice   25   50000  5000.0
1      Bob   30   60000  6000.0
2  Charlie   35   70000  7000.0
3    David   40   80000  8000.0
4      Eva   45   90000  9000.0

Filtered DataFrame where 'Salary' > 60000:
      Name  Age  Salary   Bonus
2  Charlie   35   70000  7000.0
3    David   40   80000  8000.0
4      Eva   45   90000  9000.0

Grouped DataFrame by 'Age':
        Name  Salary   Bonus
Age                         
25     Alice   50000  5000.0

<ipython-input-2-6f219f5f69c1>:62: FutureWarning: The provided callable <function mean at 0x7f6ae90ebd90> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pivot_df = merged_df.pivot_table(values='Salary', index='Department', columns='Age', aggfunc=np.mean)
